version: '3'

services:

  database:
    image: mysql
    container_name: db_byecine-v2
    restart: always
    volumes:
      - ./data:/var/lib/mysql:rw
    env_file:
      - .env
    networks:
      - byecine-v2


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_byecine-v2
    restart: always
    depends_on:
        - database
    ports:
        - 8752:80
    environment:
        PMA_HOST: database
    networks:
        - byecine-v2

  www:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    container_name: www_byecine-v2
    ports:
      - "8751:8000"
    volumes:
        - ./:/var/www:cached
        - ./.docker/php/vhosts:/etc/apache2/sites-enabled
    restart: always
    env_file:
      - .env
    networks:
        - byecine-v2

networks:
  byecine-v2:
